# Generated by Django 5.2.4 on 2025-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_productgallery_reviewrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_description",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
