# Generated by Django 5.2.4 on 2025-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
